package installers

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const defaultSkillsNamespace = "striatum-"

var generatedSkillVersionRE = regexp.MustCompile(`Generated by striatum\s+([^\s<]+)`)

// SkillsHealthParams configure the doctor-side skill-pack skew check.
type SkillsHealthParams struct {
	Target         string
	Home           string
	CurrentVersion string
	Namespace      string
}

// SkillHealthItem is one stale/missing generated Striatum skill-pack finding.
type SkillHealthItem struct {
	Scope            string   `json:"scope"`
	Profile          string   `json:"profile"`
	Path             string   `json:"path"`
	Status           string   `json:"status"`
	InstalledVersion string   `json:"installed_version,omitempty"`
	CurrentVersion   string   `json:"current_version"`
	MissingFiles     []string `json:"missing_files,omitempty"`
	RecoveryCommand  string   `json:"recovery_command"`
}

// SkillsHealthResult is the structured block returned by doctor.
type SkillsHealthResult struct {
	Checked        bool              `json:"checked"`
	CurrentVersion string            `json:"current_version"`
	Items          []SkillHealthItem `json:"items"`
}

// CheckSkillsHealth scans the project and user scopes for generated Striatum
// skill packs that are missing files, older than the running binary, or stale
// enough by header version to likely mislead an agent.
func CheckSkillsHealth(p SkillsHealthParams) (SkillsHealthResult, error) {
	if p.Namespace == "" {
		p.Namespace = defaultSkillsNamespace
	}
	result := SkillsHealthResult{Checked: true, CurrentVersion: p.CurrentVersion}
	seen := map[string]struct{}{}
	for _, scope := range []string{"project", "user"} {
		root, err := scopeBase(p.Target, p.Home, scope)
		if err != nil {
			return result, err
		}
		for _, profile := range SkillsAllProfilesOrder {
			item, ok := skillManifestHealth(root, scope, profile, p.Namespace, p.CurrentVersion)
			if ok {
				seen[item.Path] = struct{}{}
				if doc := loadManifest(skillsManifestPath(root, profile, p.Namespace), skillsManifestSchema); doc != nil {
					for _, file := range doc.Files {
						seen[displayPath(filepath.Join(root, filepath.FromSlash(file.Path)))] = struct{}{}
					}
				}
				result.Items = append(result.Items, item)
			}
		}
		headerItems := generatedSkillHeaderHealth(root, scope, p.Namespace, p.CurrentVersion, seen)
		result.Items = append(result.Items, headerItems...)
		for _, item := range headerItems {
			seen[item.Path] = struct{}{}
		}
	}
	sort.Slice(result.Items, func(i, j int) bool {
		if result.Items[i].Scope != result.Items[j].Scope {
			return result.Items[i].Scope < result.Items[j].Scope
		}
		if result.Items[i].Profile != result.Items[j].Profile {
			return result.Items[i].Profile < result.Items[j].Profile
		}
		return result.Items[i].Path < result.Items[j].Path
	})
	return result, nil
}

// SkillsHealthWarnings renders doctor warning strings for stale skill findings.
func SkillsHealthWarnings(result SkillsHealthResult) []string {
	warnings := make([]string, 0, len(result.Items))
	for _, item := range result.Items {
		switch item.Status {
		case "skills_missing":
			warnings = append(warnings, fmt.Sprintf(
				"skills_missing: %s %s generated Striatum skill manifest %s is missing %d file(s); run `%s`",
				item.Scope, item.Profile, item.Path, len(item.MissingFiles), item.RecoveryCommand,
			))
		case "skills_outdated":
			warnings = append(warnings, fmt.Sprintf(
				"skills_outdated: %s %s generated Striatum skill manifest %s was produced by %s, current is %s; run `%s`",
				item.Scope, item.Profile, item.Path, fallbackVersion(item.InstalledVersion), item.CurrentVersion, item.RecoveryCommand,
			))
		case "skills_template_stale":
			warnings = append(warnings, fmt.Sprintf(
				"skills_outdated: %s %s generated Striatum skill manifest %s has stale bundled template hashes; run `%s`",
				item.Scope, item.Profile, item.Path, item.RecoveryCommand,
			))
		case "skills_header_stale":
			warnings = append(warnings, fmt.Sprintf(
				"skills_outdated: %s %s generated Striatum skill %s was produced by %s, current is %s; run `%s`",
				item.Scope, item.Profile, item.Path, fallbackVersion(item.InstalledVersion), item.CurrentVersion, item.RecoveryCommand,
			))
		}
	}
	return warnings
}

func cleanupStalePeerSkillBundles(p SkillsParams) ([]fileResult, error) {
	if p.Namespace == "" {
		p.Namespace = defaultSkillsNamespace
	}
	out := []fileResult{}
	for _, scope := range []string{"project", "user"} {
		if scope == p.Scope {
			continue
		}
		root, err := scopeBase(p.Target, p.Home, scope)
		if err != nil {
			return nil, err
		}
		manifestPath := skillsManifestPath(root, p.Profile, p.Namespace)
		doc := loadManifest(manifestPath, skillsManifestSchema)
		if doc == nil || doc.Profile != p.Profile || doc.Namespace != p.Namespace {
			continue
		}
		if !skillManifestStale(doc, p.Profile, p.Namespace, p.Version) {
			continue
		}
		results, err := cleanupManifestOwnedSkillFiles(root, manifestPath, doc, p.Force, p.DryRun)
		if err != nil {
			return nil, err
		}
		out = append(out, results...)
	}
	return out, nil
}

func cleanupManifestOwnedSkillFiles(root, manifestPath string, doc *manifestDoc, force, dryRun bool) ([]fileResult, error) {
	results := make([]fileResult, 0, len(doc.Files)+1)
	for _, entry := range doc.Files {
		abs := filepath.Join(root, filepath.FromSlash(entry.Path))
		data, err := os.ReadFile(abs)
		if err == nil {
			sha := sha256Hex(data)
			if sha != entry.SHA256 && !force {
				return nil, fmt.Errorf("stale %s %s skill pack has operator edits at %s; rerun with --force or remove the stale pack",
					doc.Scope, doc.Profile, abs)
			}
			shaBefore := sha
			status := "removed"
			if dryRun {
				status = "dry_run_remove"
			} else if err := os.Remove(abs); err != nil && !os.IsNotExist(err) {
				return nil, err
			}
			results = append(results, fileResult{Path: entry.Path, Status: status, SHA256Before: &shaBefore, SHA256After: ""})
			if !dryRun {
				_ = os.Remove(filepath.Dir(abs))
			}
			continue
		}
		if !os.IsNotExist(err) {
			return nil, err
		}
		results = append(results, fileResult{Path: entry.Path, Status: "missing", SHA256After: ""})
	}
	status := "removed"
	if dryRun {
		status = "dry_run_remove"
	} else if err := os.Remove(manifestPath); err != nil && !os.IsNotExist(err) {
		return nil, err
	}
	if !dryRun {
		_ = os.Remove(filepath.Dir(manifestPath))
	}
	results = append(results, fileResult{
		Path:        filepath.ToSlash(relOrAbs(root, manifestPath)),
		Status:      status,
		SHA256After: "",
	})
	return results, nil
}

func skillManifestHealth(root, scope, profile, namespace, currentVersion string) (SkillHealthItem, bool) {
	manifestPath := skillsManifestPath(root, profile, namespace)
	doc := loadManifest(manifestPath, skillsManifestSchema)
	if doc == nil {
		return SkillHealthItem{}, false
	}
	if doc.Profile != profile || doc.Namespace != namespace {
		return SkillHealthItem{}, false
	}
	item := SkillHealthItem{
		Scope:            scope,
		Profile:          profile,
		Path:             displayPath(manifestPath),
		InstalledVersion: doc.StriatumVersion,
		CurrentVersion:   currentVersion,
		RecoveryCommand:  skillsRecoveryCommand(root, scope, profile),
	}
	for _, entry := range doc.Files {
		if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(entry.Path))); os.IsNotExist(err) {
			item.MissingFiles = append(item.MissingFiles, entry.Path)
		}
	}
	if len(item.MissingFiles) > 0 {
		item.Status = "skills_missing"
		return item, true
	}
	if versionOlder(doc.StriatumVersion, currentVersion) {
		item.Status = "skills_outdated"
		return item, true
	}
	if manifestTemplateStale(doc, profile, namespace, currentVersion) {
		item.Status = "skills_template_stale"
		return item, true
	}
	return SkillHealthItem{}, false
}

func generatedSkillHeaderHealth(root, scope, namespace, currentVersion string, seen map[string]struct{}) []SkillHealthItem {
	candidates := generatedSkillCandidates(root, namespace)
	items := []SkillHealthItem{}
	for _, candidate := range candidates {
		display := displayPath(candidate.path)
		if _, ok := seen[display]; ok {
			continue
		}
		body, err := os.ReadFile(candidate.path)
		if err != nil {
			continue
		}
		version, ok := generatedSkillVersion(string(body))
		if !ok || !versionMoreThanMinorBehind(version, currentVersion) {
			continue
		}
		items = append(items, SkillHealthItem{
			Scope:            scope,
			Profile:          candidate.profile,
			Path:             display,
			Status:           "skills_header_stale",
			InstalledVersion: version,
			CurrentVersion:   currentVersion,
			RecoveryCommand:  skillsRecoveryCommand(root, scope, candidate.profile),
		})
	}
	return items
}

type generatedSkillCandidate struct {
	profile string
	path    string
}

func generatedSkillCandidates(root, namespace string) []generatedSkillCandidate {
	var out []generatedSkillCandidate
	for _, pattern := range []struct {
		profile string
		glob    string
	}{
		{"claude_code", filepath.Join(root, ".claude", "skills", namespace+"*", "SKILL.md")},
		{"agy", filepath.Join(root, ".agy", "skills", namespace+"*", "SKILL.md")},
		{"codex", filepath.Join(root, ".codex", "agents", namespace+"*.md")},
		{"generic", filepath.Join(root, namespace+"*AGENT_GUIDE.md")},
	} {
		matches, _ := filepath.Glob(pattern.glob)
		for _, match := range matches {
			out = append(out, generatedSkillCandidate{profile: pattern.profile, path: match})
		}
	}
	return out
}

func generatedSkillVersion(body string) (string, bool) {
	match := generatedSkillVersionRE.FindStringSubmatch(body)
	if len(match) != 2 {
		return "", false
	}
	version := strings.TrimRight(match[1], ".")
	if version == "" {
		return "", false
	}
	return version, true
}

func skillManifestStale(doc *manifestDoc, profile, namespace, currentVersion string) bool {
	if versionOlder(doc.StriatumVersion, currentVersion) {
		return true
	}
	return manifestTemplateStale(doc, profile, namespace, currentVersion)
}

func manifestTemplateStale(doc *manifestDoc, profile, namespace, currentVersion string) bool {
	plan, err := skillsPlan(profile, namespace, renderContext{StriatumVersion: currentVersion, Namespace: namespace})
	if err != nil {
		return false
	}
	currentTemplates := map[string]string{}
	for _, entry := range plan {
		currentTemplates[entry.Path] = entry.TemplateSHA256
	}
	for _, entry := range doc.Files {
		if currentTemplates[entry.Path] != "" && currentTemplates[entry.Path] != entry.TemplateSHA256 {
			return true
		}
	}
	return false
}

func skillsRecoveryCommand(root, scope, profile string) string {
	if scope == "project" && root != "" {
		return fmt.Sprintf("striatum --repo %q skills install --profile %s --scope %s --force", root, profile, scope)
	}
	return fmt.Sprintf("striatum skills install --profile %s --scope %s --force", profile, scope)
}

func versionOlder(installed, current string) bool {
	i, okI := parseVersion(installed)
	c, okC := parseVersion(current)
	if !okI || !okC {
		return false
	}
	return compareVersion(i, c) < 0
}

func versionMoreThanMinorBehind(installed, current string) bool {
	i, okI := parseVersion(installed)
	c, okC := parseVersion(current)
	if !okI || !okC {
		return false
	}
	if c.major != i.major {
		return c.major > i.major
	}
	return c.minor-i.minor > 1
}

type parsedVersion struct {
	major int
	minor int
	patch int
}

func parseVersion(value string) (parsedVersion, bool) {
	text := strings.TrimPrefix(strings.TrimSpace(value), "v")
	if text == "" {
		return parsedVersion{}, false
	}
	text = strings.SplitN(text, "-", 2)[0]
	parts := strings.Split(text, ".")
	if len(parts) < 2 {
		return parsedVersion{}, false
	}
	nums := []int{0, 0, 0}
	for i := 0; i < len(parts) && i < 3; i++ {
		n, err := strconv.Atoi(parts[i])
		if err != nil {
			return parsedVersion{}, false
		}
		nums[i] = n
	}
	return parsedVersion{major: nums[0], minor: nums[1], patch: nums[2]}, true
}

func compareVersion(a, b parsedVersion) int {
	if a.major != b.major {
		return a.major - b.major
	}
	if a.minor != b.minor {
		return a.minor - b.minor
	}
	return a.patch - b.patch
}

func relOrAbs(root, path string) string {
	rel, err := filepath.Rel(root, path)
	if err != nil || strings.HasPrefix(rel, "..") {
		return path
	}
	return rel
}

func displayPath(path string) string {
	home, err := os.UserHomeDir()
	if err == nil && home != "" {
		if rel, relErr := filepath.Rel(home, path); relErr == nil && rel != "." && !strings.HasPrefix(rel, "..") {
			return "~/" + filepath.ToSlash(rel)
		}
	}
	return filepath.ToSlash(path)
}

func fallbackVersion(value string) string {
	if strings.TrimSpace(value) == "" {
		return "unknown"
	}
	return value
}
