-- RFC 0110 Release N+1 Slice 1 — owner bundle 0001: authority schema + v3 hash
-- + Phase 0 (audit_only) write-boundary.
--
-- Applied OUT-OF-BAND as the database owner (never by the runtime role; RFC 0079
-- §5). Additive + opt-in: a daemon with this bundle UNapplied behaves exactly
-- like release N. The whole bundle is applied in one transaction by
-- ApplyOwnerBundles, which stamps owner_bundle_meta last.

-- pgcrypto supplies digest(bytea,'sha256'). Install into striatumd when absent so
-- the hardened SD functions can resolve it; tolerate a pre-existing install
-- elsewhere (the SD functions keep public on their pinned search_path for it).
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pgcrypto') THEN
    CREATE EXTENSION pgcrypto WITH SCHEMA striatumd;
  END IF;
END
$$;

-- Owner-bundle version bookkeeping (owner-only).
CREATE TABLE IF NOT EXISTS striatumd.owner_bundle_meta (
  version integer PRIMARY KEY,
  label text NOT NULL,
  sha256 text NOT NULL,
  daemon_version text NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT now()
);

-- Capability stamps the startup parity checker reads (RFC 0110 §8.2).
CREATE TABLE IF NOT EXISTS striatumd.schema_authority (
  capability text PRIMARY KEY,
  requires_daemon_auth boolean NOT NULL DEFAULT false,
  bundle_version integer NOT NULL,
  stamped_at timestamptz NOT NULL DEFAULT now()
);

-- Daemon-authority registry (RFC 0110 §4.1). Owner-only: the runtime role gets
-- no privilege (T-REGISTRY-ACL). role_name/instance_id are diagnostic labels for
-- the rotator probe (§9.4); the secret itself is the authority (§4.6).
CREATE TABLE IF NOT EXISTS striatumd.daemon_auth_registry (
  instance_id text NOT NULL,
  role_name text NOT NULL,
  digest text NOT NULL,
  salt text NOT NULL,
  rotated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (instance_id, role_name)
);

-- Auth posture log (RFC 0110 §12). Owner-only; written through a redactor.
CREATE TABLE IF NOT EXISTS striatumd.daemon_auth_log (
  log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts timestamptz NOT NULL DEFAULT now(),
  event text NOT NULL,
  detail jsonb
);

-- assert_daemon_authority: every owner-owned SD write function begins here. The
-- presented per-process secret must match a registry digest (sha256(secret‖salt)
-- per row's salt); a runtime-role caller holding only the DSN cannot forge it.
-- Role-agnostic: the secret is authority, so this works whether the daemon
-- connects directly as the runtime role or a test reaches it via SET ROLE.
CREATE OR REPLACE FUNCTION striatumd.assert_daemon_authority()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = striatumd, public, pg_temp
AS $$
DECLARE
  presented text;
  matched boolean;
BEGIN
  presented := current_setting('striatum.daemon_auth', true);
  IF presented IS NULL OR presented = '' THEN
    RAISE EXCEPTION USING ERRCODE = '28000',
      MESSAGE = 'daemon authority secret missing';
  END IF;
  SELECT EXISTS (
    SELECT 1
      FROM striatumd.daemon_auth_registry r
     WHERE encode(digest(convert_to(presented || r.salt, 'UTF8'), 'sha256'), 'hex') = r.digest
  ) INTO matched;
  IF NOT matched THEN
    RAISE EXCEPTION USING ERRCODE = '28000',
      MESSAGE = 'daemon authority mismatch';
  END IF;
END
$$;

-- v3 length-prefixed canonical encoder (RFC 0110 §5.1): escaping-free and
-- key-order-free, byte-identical to the Go V3RowHash builder. string s ->
-- octet_length(utf8(s)) || ':' || utf8(s); null -> '-1:'.
CREATE OR REPLACE FUNCTION striatumd.audit_v3_enc_text(v text)
RETURNS bytea
LANGUAGE sql
IMMUTABLE
SET search_path = striatumd, public, pg_temp
AS $$
  SELECT CASE
    WHEN v IS NULL THEN convert_to('-1:', 'UTF8')
    ELSE convert_to(octet_length(convert_to(v, 'UTF8'))::text || ':', 'UTF8') || convert_to(v, 'UTF8')
  END
$$;

-- v3 row hash over the 15 audit fields in fixed declared order. Integers are
-- rendered to decimal ASCII then length-prefixed like a string; the timestamp is
-- second-truncated UTC RFC3339, independent of the session TimeZone.
CREATE OR REPLACE FUNCTION striatumd.audit_v3_row_hash(
  p_ts timestamptz,
  p_schema_version integer,
  p_hash_format_version integer,
  p_daemon_version text,
  p_client_id text,
  p_repository_id text,
  p_method text,
  p_decision text,
  p_denial_reason text,
  p_transport text,
  p_request_id text,
  p_exit_code integer,
  p_params_sha256 text,
  p_previous_hash text,
  p_segment_id bigint
)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = striatumd, public, pg_temp
AS $$
  SELECT encode(digest(
    striatumd.audit_v3_enc_text(to_char(p_ts AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')) ||
    striatumd.audit_v3_enc_text(p_schema_version::text) ||
    striatumd.audit_v3_enc_text(p_hash_format_version::text) ||
    striatumd.audit_v3_enc_text(p_daemon_version) ||
    striatumd.audit_v3_enc_text(p_client_id) ||
    striatumd.audit_v3_enc_text(p_repository_id) ||
    striatumd.audit_v3_enc_text(p_method) ||
    striatumd.audit_v3_enc_text(p_decision) ||
    striatumd.audit_v3_enc_text(p_denial_reason) ||
    striatumd.audit_v3_enc_text(p_transport) ||
    striatumd.audit_v3_enc_text(p_request_id) ||
    striatumd.audit_v3_enc_text(p_exit_code::text) ||
    striatumd.audit_v3_enc_text(p_params_sha256) ||
    striatumd.audit_v3_enc_text(p_previous_hash) ||
    striatumd.audit_v3_enc_text(p_segment_id::text),
    'sha256'), 'hex')
$$;

-- append_audit_row: the SD-only write path for audit_log (RFC 0110 §4.4, §5).
-- Asserts daemon authority, locks the chain head, opens/uses the current
-- segment, computes the v3 hash in-DB, and appends — atomic with whatever
-- transaction the caller is in. Writes hash_format_version = 3.
CREATE OR REPLACE FUNCTION striatumd.append_audit_row(
  p_daemon_version text,
  p_client_id text,
  p_repository_id text,
  p_method text,
  p_decision text,
  p_denial_reason text,
  p_transport text,
  p_request_id text,
  p_ok boolean,
  p_params_sha256 text
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = striatumd, public, pg_temp
AS $$
DECLARE
  v_last_hash text;
  v_segment_id bigint;
  v_ts timestamptz := date_trunc('second', now());
  v_exit_code integer := CASE WHEN p_ok THEN NULL ELSE 10 END;
  v_row_hash text;
  v_audit_id bigint;
BEGIN
  PERFORM striatumd.assert_daemon_authority();

  SELECT last_hash INTO v_last_hash
    FROM striatumd.audit_chain_head
   WHERE singleton = true
     FOR UPDATE;

  SELECT segment_id INTO v_segment_id
    FROM striatumd.audit_segments
   WHERE state = 'open'
   ORDER BY segment_id DESC
   LIMIT 1;
  IF v_segment_id IS NULL THEN
    INSERT INTO striatumd.audit_segments(opened_at, state, retention_state)
    VALUES (now(), 'open', 'active')
    RETURNING segment_id INTO v_segment_id;
  END IF;

  v_row_hash := striatumd.audit_v3_row_hash(
    v_ts, 1, 3, p_daemon_version, p_client_id, p_repository_id, p_method,
    p_decision, p_denial_reason, p_transport, p_request_id, v_exit_code,
    p_params_sha256, v_last_hash, v_segment_id);

  INSERT INTO striatumd.audit_log (
    ts, schema_version, hash_format_version, daemon_version,
    client_id, repository_id, method, decision, denial_reason,
    transport, request_id, exit_code, params_sha256, previous_hash,
    row_hash, segment_id
  ) VALUES (
    v_ts, 1, 3, p_daemon_version,
    p_client_id, p_repository_id, p_method, p_decision, p_denial_reason,
    p_transport, p_request_id, v_exit_code, p_params_sha256, v_last_hash,
    v_row_hash, v_segment_id
  ) RETURNING audit_id INTO v_audit_id;

  UPDATE striatumd.audit_chain_head
     SET last_audit_id = v_audit_id, last_hash = v_row_hash, updated_at = now()
   WHERE singleton = true;

  RETURN v_audit_id;
END
$$;

-- SD-hardening (RFC 0110 §6): no PUBLIC execute on the owner-owned functions;
-- the runtime role gets EXECUTE only on the sanctioned write path.
REVOKE ALL ON FUNCTION striatumd.assert_daemon_authority() FROM PUBLIC;
REVOKE ALL ON FUNCTION striatumd.append_audit_row(text, text, text, text, text, text, text, text, boolean, text) FROM PUBLIC;

-- The canonical runtime role. Created idempotently so the bundle is
-- self-contained; production also provisions it via daemon doctor.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'striatumd_rw') THEN
    CREATE ROLE striatumd_rw;
  END IF;
END
$$;

-- Phase 0 (audit_only): the runtime role may no longer INSERT audit_log
-- directly; the only write path is the SD function (T-42501-P0, T-EXEC-AUTH).
REVOKE INSERT ON striatumd.audit_log FROM striatumd_rw;
GRANT EXECUTE ON FUNCTION striatumd.append_audit_row(text, text, text, text, text, text, text, text, boolean, text) TO striatumd_rw;

-- Capability stamp the binary's startup parity check verifies (RFC 0110 §8.2).
INSERT INTO striatumd.schema_authority(capability, requires_daemon_auth, bundle_version)
VALUES ('audit_sd_append', true, 1)
ON CONFLICT (capability) DO NOTHING;
