"""Command line interface for the striatum MVP.

This package re-exports every public CLI symbol so callers (the
``striatum.cli:main`` console entry point, ``striatum.api``, ``striatum.mcp``,
``striatum.dashboard``, and the test suite) can keep importing from
``striatum.cli`` without needing to know about the internal split.
"""

from __future__ import annotations

from striatum.cli.dispatch import dispatch, main
from striatum.cli.evidence import (
    EVIDENCE_FREE_TEXT_PLACEHOLDER,
    EVIDENCE_POLICY,
    dependency_summary,
    evidence_artifact_summaries,
    evidence_export,
    evidence_job_summaries,
    evidence_snapshot,
    redact_evidence_payload,
    render_evidence_markdown,
)
from striatum.cli.introspect import (
    blocked_downstream_jobs,
    blocker_summaries,
    blockers_for_job,
    claimable_jobs_by_role_lane,
    dependency_context,
    doctor,
    downstream_jobs,
    events_for,
    events_for_process,
    human_checkpoint_context,
    jobs_for_run,
    jobs_for_session,
    latest_non_accepting_verdicts,
    latest_verdict_row,
    next_actions,
    recent_events_for_run,
    run_graph,
    status,
    table_exists,
    verdicts_for_artifact,
    why,
)
from striatum.cli.mutations import (
    ack_work,
    block_work,
    branch_confirm,
    checkpoint_resolve,
    current_git_branch,
    decision_record,
    git_create_or_checkout_branch,
    heartbeat,
    prevalidate_submit_review,
    register_session,
    release_work,
    render_decision_markdown,
    run_start,
    send_message,
    submit_review,
    verdict_work,
)
from striatum.cli.list_commands import (
    list_artifacts,
    list_jobs,
    list_runs,
    list_sessions,
    list_workflows,
)
from striatum.cli.parser import add_work_identity, build_parser
from striatum.cli.recovery import cancel_job, requeue_stale, stale_leases
from striatum.cli.run_summary import (
    render_run_summary_markdown,
    run_summary_export,
    run_summary_snapshot,
)
from striatum.cli.supervise import (
    SUPERVISOR_ACTIVE_STATES,
    supervise_list,
    supervise_send,
    supervise_start,
    supervise_status,
    supervise_stop,
)
from striatum.cli.workflow_init import workflow_init
from striatum.cli.worktree import worktree_create, worktree_list, worktree_release

__all__ = [
    "EVIDENCE_FREE_TEXT_PLACEHOLDER",
    "EVIDENCE_POLICY",
    "SUPERVISOR_ACTIVE_STATES",
    "ack_work",
    "add_work_identity",
    "block_work",
    "blocked_downstream_jobs",
    "blocker_summaries",
    "blockers_for_job",
    "branch_confirm",
    "build_parser",
    "cancel_job",
    "checkpoint_resolve",
    "claimable_jobs_by_role_lane",
    "current_git_branch",
    "decision_record",
    "dependency_context",
    "dependency_summary",
    "dispatch",
    "doctor",
    "downstream_jobs",
    "events_for",
    "events_for_process",
    "evidence_artifact_summaries",
    "evidence_export",
    "evidence_job_summaries",
    "evidence_snapshot",
    "git_create_or_checkout_branch",
    "heartbeat",
    "human_checkpoint_context",
    "jobs_for_run",
    "jobs_for_session",
    "latest_non_accepting_verdicts",
    "latest_verdict_row",
    "list_artifacts",
    "list_jobs",
    "list_runs",
    "list_sessions",
    "list_workflows",
    "main",
    "next_actions",
    "prevalidate_submit_review",
    "recent_events_for_run",
    "redact_evidence_payload",
    "register_session",
    "release_work",
    "render_decision_markdown",
    "render_evidence_markdown",
    "render_run_summary_markdown",
    "requeue_stale",
    "run_graph",
    "run_start",
    "run_summary_export",
    "run_summary_snapshot",
    "send_message",
    "stale_leases",
    "status",
    "submit_review",
    "supervise_list",
    "supervise_send",
    "supervise_start",
    "supervise_status",
    "supervise_stop",
    "table_exists",
    "verdict_work",
    "verdicts_for_artifact",
    "why",
    "workflow_init",
    "worktree_create",
    "worktree_list",
    "worktree_release",
]
