CREATE SCHEMA IF NOT EXISTS striatumd;

CREATE TABLE IF NOT EXISTS striatumd.schema_meta (
  key text PRIMARY KEY,
  value text NOT NULL
);

CREATE TABLE IF NOT EXISTS striatumd.schema_migrations (
  version integer PRIMARY KEY,
  label text NOT NULL,
  sha256 text NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT now(),
  daemon_version text NOT NULL
);

CREATE TABLE IF NOT EXISTS striatumd.daemon_meta (
  key text PRIMARY KEY,
  value text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS striatumd.repositories (
  repository_id text PRIMARY KEY,
  repo_identity text NOT NULL,
  repo_root text NOT NULL,
  state_db_path text NOT NULL,
  display_name text NOT NULL,
  registered_at timestamptz NOT NULL,
  removed_at timestamptz,
  last_seen_at timestamptz,
  last_schema_version integer NOT NULL,
  state text NOT NULL CHECK (state IN ('active','missing','disabled','removed')),
  settings_json jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_striatumd_active_repo_identity
  ON striatumd.repositories(repo_identity)
  WHERE state IN ('active','missing','disabled');

CREATE UNIQUE INDEX IF NOT EXISTS uq_striatumd_active_repo_root
  ON striatumd.repositories(repo_root)
  WHERE state IN ('active','missing','disabled');

CREATE TABLE IF NOT EXISTS striatumd.clients (
  client_id text PRIMARY KEY,
  client_kind text NOT NULL,
  display_name text NOT NULL,
  token_id text NOT NULL UNIQUE,
  token_hash text NOT NULL,
  token_salt text NOT NULL,
  created_at timestamptz NOT NULL,
  expires_at timestamptz,
  revoked_at timestamptz,
  last_used_at timestamptz
);

CREATE TABLE IF NOT EXISTS striatumd.client_capabilities (
  capability_id text PRIMARY KEY,
  client_id text NOT NULL REFERENCES striatumd.clients(client_id),
  repository_id text REFERENCES striatumd.repositories(repository_id),
  capability text NOT NULL CHECK (capability IN ('read','write','review','claim','apply','admin','recovery')),
  granted_at timestamptz NOT NULL,
  expires_at timestamptz,
  revoked_at timestamptz,
  revoked_reason text
);

CREATE TABLE IF NOT EXISTS striatumd.audit_segments (
  segment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opened_at timestamptz NOT NULL,
  closed_at timestamptz,
  first_audit_id bigint,
  last_audit_id bigint,
  first_hash text,
  last_hash text,
  previous_segment_id bigint,
  previous_segment_last_hash text,
  next_segment_first_previous_hash text,
  retention_state text NOT NULL DEFAULT 'active',
  state text NOT NULL CHECK (state IN ('open','closed','purged'))
);

CREATE TABLE IF NOT EXISTS striatumd.audit_log (
  audit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts timestamptz NOT NULL,
  schema_version integer NOT NULL,
  hash_format_version integer NOT NULL,
  daemon_version text NOT NULL,
  client_id text,
  repository_id text,
  method text NOT NULL,
  decision text NOT NULL,
  denial_reason text,
  transport text NOT NULL,
  request_id text,
  exit_code integer,
  params_sha256 text NOT NULL,
  previous_hash text,
  row_hash text NOT NULL UNIQUE,
  segment_id bigint NOT NULL REFERENCES striatumd.audit_segments(segment_id)
);

CREATE TABLE IF NOT EXISTS striatumd.audit_chain_head (
  singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
  last_audit_id bigint,
  last_hash text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS striatumd.scheduler_cursors (
  repository_id text NOT NULL REFERENCES striatumd.repositories(repository_id),
  run_id text NOT NULL,
  cursor_kind text NOT NULL,
  last_sweep_at timestamptz,
  next_sweep_after timestamptz,
  last_result_json jsonb,
  state text NOT NULL CHECK (state IN ('active','in_progress','sweep_degraded','removed')),
  PRIMARY KEY(repository_id, run_id, cursor_kind)
);

CREATE TABLE IF NOT EXISTS striatumd.rpc_request_log (
  request_id text PRIMARY KEY,
  client_id text,
  repository_id text,
  method text NOT NULL,
  params_hash text NOT NULL,
  response_hash text,
  decision text NOT NULL,
  audit_id bigint,
  envelope_version text NOT NULL,
  daemon_version text NOT NULL,
  schema_version integer NOT NULL,
  started_at timestamptz NOT NULL,
  finished_at timestamptz,
  expires_at timestamptz
);

CREATE TABLE IF NOT EXISTS striatumd.client_sessions (
  client_session_id text PRIMARY KEY,
  client_id text REFERENCES striatumd.clients(client_id),
  transport text NOT NULL,
  envelope_version text NOT NULL,
  methods_etag text,
  opened_at timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL,
  closed_at timestamptz
);

CREATE OR REPLACE FUNCTION striatumd.refuse_audit_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'daemon audit rows are append-only';
END;
$$;

DROP TRIGGER IF EXISTS audit_log_no_update ON striatumd.audit_log;
CREATE TRIGGER audit_log_no_update
BEFORE UPDATE ON striatumd.audit_log
FOR EACH ROW EXECUTE FUNCTION striatumd.refuse_audit_change();

DROP TRIGGER IF EXISTS audit_log_no_delete ON striatumd.audit_log;
CREATE TRIGGER audit_log_no_delete
BEFORE DELETE ON striatumd.audit_log
FOR EACH ROW EXECUTE FUNCTION striatumd.refuse_audit_change();

CREATE OR REPLACE FUNCTION striatumd.refuse_closed_segment_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.state <> 'open' THEN
    RAISE EXCEPTION 'closed daemon audit segments are append-only';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS audit_segments_closed_no_update ON striatumd.audit_segments;
CREATE TRIGGER audit_segments_closed_no_update
BEFORE UPDATE ON striatumd.audit_segments
FOR EACH ROW EXECUTE FUNCTION striatumd.refuse_closed_segment_change();

DROP TRIGGER IF EXISTS audit_segments_no_delete ON striatumd.audit_segments;
CREATE TRIGGER audit_segments_no_delete
BEFORE DELETE ON striatumd.audit_segments
FOR EACH ROW EXECUTE FUNCTION striatumd.refuse_audit_change();

INSERT INTO striatumd.schema_meta(key, value)
VALUES
  ('substrate', 'postgres'),
  ('substrate_version', '1'),
  ('pg_major_at_bootstrap', current_setting('server_version_num')),
  ('bootstrapped_at', now()::text)
ON CONFLICT (key) DO NOTHING;

INSERT INTO striatumd.audit_segments(opened_at, state, retention_state)
SELECT now(), 'open', 'active'
WHERE NOT EXISTS (SELECT 1 FROM striatumd.audit_segments WHERE state = 'open');

INSERT INTO striatumd.audit_chain_head(singleton)
VALUES (true)
ON CONFLICT (singleton) DO NOTHING;
