package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
)

type contract struct {
	CLIRoutes []cliRoute    `json:"cli_routes"`
	Methods   []methodEntry `json:"methods"`
}

type cliRoute struct {
	Command    string  `json:"command"`
	Subcommand *string `json:"subcommand"`
	Method     string  `json:"method"`
	Params     string  `json:"params"`
}

type methodEntry struct {
	Method              string  `json:"method"`
	RequiredCapability  *string `json:"required_capability"`
	RepositoryScopeMode string  `json:"repository_scope_mode"`
	Deprecated          bool    `json:"deprecated"`
}

func main() {
	contractPath := flag.String("contract", "", "daemon method contract")
	outPath := flag.String("out", "", "generated Go output")
	flag.Parse()
	if *contractPath == "" || *outPath == "" {
		fmt.Fprintln(os.Stderr, "usage: routergen -contract path -out path")
		os.Exit(2)
	}
	body, err := os.ReadFile(*contractPath)
	if err != nil {
		fatal(err)
	}
	var parsed contract
	if err := json.Unmarshal(body, &parsed); err != nil {
		fatal(err)
	}
	methods := map[string]methodEntry{}
	for _, entry := range parsed.Methods {
		methods[entry.Method] = entry
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by go/pkg/cli/routergen from contracts/daemon_methods.json; DO NOT EDIT.\n\n")
	buf.WriteString("package routes\n\n")
	buf.WriteString("var generatedRoutes = []Route{\n")
	for _, route := range parsed.CLIRoutes {
		entry, ok := methods[route.Method]
		if !ok {
			fatal(fmt.Errorf("cli route %s references unknown method %s", route.Command, route.Method))
		}
		subcommand := ""
		if route.Subcommand != nil {
			subcommand = *route.Subcommand
		}
		capability := ""
		if entry.RequiredCapability != nil {
			capability = *entry.RequiredCapability
		}
		fmt.Fprintf(&buf, "{Command:%q, Subcommand:%q, Method:%q, ParamsGroup:%q, RequiredCapability:%q, RepositoryScopeMode:%q, Deprecated:%t},\n",
			route.Command, subcommand, route.Method, route.Params, capability, entry.RepositoryScopeMode, entry.Deprecated)
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fatal(err)
	}
	if err := os.WriteFile(*outPath, formatted, 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
