package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
)

type contract struct {
	CLIRoutes []cliRoute    `json:"cli_routes"`
	Methods   []methodEntry `json:"methods"`
}

type cliRoute struct {
	Command    string  `json:"command"`
	Subcommand *string `json:"subcommand"`
	Method     string  `json:"method"`
	Params     string  `json:"params"`
}

type methodEntry struct {
	Method              string  `json:"method"`
	RequiredCapability  *string `json:"required_capability"`
	RepositoryScope     *bool   `json:"repository_scope"`
	RepositoryScopeMode string  `json:"repository_scope_mode"`
	ParamsSchemaVersion int     `json:"params_schema_version"`
	AuditClass          string  `json:"audit_class"`
	MinEnvelope         int     `json:"min_envelope"`
	Deprecated          bool    `json:"deprecated"`
}

func main() {
	contractPath := flag.String("contract", "", "daemon method contract")
	outPath := flag.String("out", "", "generated output")
	mode := flag.String("mode", "routes", "generation mode: routes, rpc-registry, markdown-tables")
	flag.Parse()

	if *contractPath == "" || *outPath == "" {
		fmt.Fprintln(os.Stderr, "usage: routergen -contract path -out path [-mode routes|rpc-registry|markdown-tables]")
		os.Exit(2)
	}

	body, err := os.ReadFile(*contractPath)
	if err != nil {
		fatal(err)
	}
	var parsed contract
	if err := json.Unmarshal(body, &parsed); err != nil {
		fatal(err)
	}

	var output []byte
	switch *mode {
	case "routes":
		output = generateRoutes(parsed, *contractPath)
	case "rpc-registry":
		output = generateRPCRegistry(parsed, *contractPath)
	case "markdown-tables":
		output = generateMarkdownTables(parsed, *contractPath)
	default:
		fatal(fmt.Errorf("unknown mode: %s", *mode))
	}

	if err := os.WriteFile(*outPath, output, 0o644); err != nil {
		fatal(err)
	}
}

func generateRoutes(parsed contract, contractPath string) []byte {
	methods := map[string]methodEntry{}
	for _, entry := range parsed.Methods {
		methods[entry.Method] = entry
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by go/pkg/cli/routergen from contracts/daemon_methods.json; DO NOT EDIT.\n\n")
	buf.WriteString("package routes\n\n")
	buf.WriteString("var generatedRoutes = []Route{\n")
	for _, route := range parsed.CLIRoutes {
		entry, ok := methods[route.Method]
		if !ok {
			fatal(fmt.Errorf("cli route %s references unknown method %s", route.Command, route.Method))
		}
		subcommand := ""
		if route.Subcommand != nil {
			subcommand = *route.Subcommand
		}
		capability := ""
		if entry.RequiredCapability != nil {
			capability = *entry.RequiredCapability
		}
		fmt.Fprintf(&buf, "{Command:%q, Subcommand:%q, Method:%q, ParamsGroup:%q, RequiredCapability:%q, RepositoryScopeMode:%q, Deprecated:%t},\n",
			route.Command, subcommand, route.Method, route.Params, capability, entry.RepositoryScopeMode, entry.Deprecated)
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fatal(err)
	}
	return formatted
}

func generateRPCRegistry(parsed contract, contractPath string) []byte {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by go/pkg/cli/routergen from contracts/daemon_methods.json; DO NOT EDIT.\n\n")
	buf.WriteString("package rpc\n\n")
	buf.WriteString("var methodEntries = []MethodEntry{\n")

	capExpr := map[string]string{
		"read":              "CapPtr(CapabilityRead)",
		"write":             "CapPtr(CapabilityWrite)",
		"review":            "CapPtr(CapabilityReview)",
		"claim":             "CapPtr(CapabilityClaim)",
		"apply":             "CapPtr(CapabilityApply)",
		"admin":             "CapPtr(CapabilityAdmin)",
		"recovery":          "CapPtr(CapabilityRecovery)",
		"surgical_recovery": "CapPtr(CapabilitySurgicalRecovery)",
	}

	scopeModeExpr := map[string]string{
		"single_repo":   "ScopeSingleRepo",
		"cross_repo":    "ScopeCrossRepo",
		"daemon_global": "ScopeDaemonGlobal",
	}

	for _, m := range parsed.Methods {
		cap := "nil"
		if m.RequiredCapability != nil {
			if expr, ok := capExpr[*m.RequiredCapability]; ok {
				cap = expr
			} else {
				fatal(fmt.Errorf("unknown capability: %s", *m.RequiredCapability))
			}
		}

		scopeMode := m.RepositoryScopeMode
		if scopeMode == "" {
			if m.RepositoryScope != nil {
				if *m.RepositoryScope {
					scopeMode = "single_repo"
				} else {
					scopeMode = "daemon_global"
				}
			} else {
				fatal(fmt.Errorf("method %s: repository_scope_mode is required", m.Method))
			}
		}

		scopeModeExprVal, ok := scopeModeExpr[scopeMode]
		if !ok {
			fatal(fmt.Errorf("unknown repository_scope_mode: %s", scopeMode))
		}

		repoScope := scopeMode == "single_repo"
		if m.RepositoryScope != nil {
			repoScope = *m.RepositoryScope
		}

		deprecated := ""
		if m.Deprecated {
			deprecated = ", Deprecated: true"
		}

		fmt.Fprintf(&buf, "\t{Method: %q, RequiredCapability: %s, RepositoryScope: %t, RepositoryScopeMode: %s, ParamsSchemaVersion: %d, AuditClass: %q, MinEnvelope: %d%s},\n",
			m.Method, cap, repoScope, scopeModeExprVal, m.ParamsSchemaVersion, m.AuditClass, m.MinEnvelope, deprecated)
	}
	buf.WriteString("}\n")

	return buf.Bytes()
}

func generateMarkdownTables(parsed contract, contractPath string) []byte {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by go/pkg/cli/routergen from contracts/daemon_methods.json; DO NOT EDIT. -->\n\n")
	buf.WriteString("# Daemon Method Tables\n\n")
	buf.WriteString("## Daemon Method Registry\n\n")
	buf.WriteString("| RPC method | Capability | Scope | Params schema | Min envelope | Deprecated |\n")
	buf.WriteString("|---|---|---|---:|---:|---:|\n")

	for _, m := range parsed.Methods {
		cap := "none"
		if m.RequiredCapability != nil {
			cap = fmt.Sprintf("`%s`", *m.RequiredCapability)
		}
		dep := "no"
		if m.Deprecated {
			dep = "yes"
		}
		fmt.Fprintf(&buf, "| `%s` | %s | `%s` | %d | %d | %s |\n",
			m.Method, cap, m.RepositoryScopeMode, m.ParamsSchemaVersion, m.MinEnvelope, dep)
	}

	buf.WriteString("\n## CLI Route Translation\n\n")
	buf.WriteString("| CLI command | RPC method | Capability | Scope |\n")
	buf.WriteString("|---|---|---|---|\n")

	methods := map[string]methodEntry{}
	for _, m := range parsed.Methods {
		methods[m.Method] = m
	}

	for _, r := range parsed.CLIRoutes {
		m, ok := methods[r.Method]
		if !ok {
			fatal(fmt.Errorf("cli route %s references unknown method %s", r.Command, r.Method))
		}
		cmd := r.Command
		if r.Subcommand != nil && *r.Subcommand != "" {
			cmd = fmt.Sprintf("%s %s", r.Command, *r.Subcommand)
		}
		cap := "none"
		if m.RequiredCapability != nil {
			cap = fmt.Sprintf("`%s`", *m.RequiredCapability)
		}
		fmt.Fprintf(&buf, "| `%s` | `%s` | %s | `%s` |\n",
			cmd, r.Method, cap, m.RepositoryScopeMode)
	}

	return buf.Bytes()
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
